export enum ExpressionKind {
    Number = "number",
    Variable = "variable",
    Constant = "constant",
    Call = "call",
    Negate = "negate",
    Not = "logical-not",
    Binary = "binary"
}

export enum BinaryOperator {
    Add = "+",
    Subtract = "-",
    Multiply = "*",
    Divide = "/",
    Power = "^",
    LessThan = "<",
    GreaterThan = ">",
    LessOrEqual = "<=",
    GreaterOrEqual = ">=",
    Equal = "==",
    NotEqual = "!=",
    And = "and",
    Or = "or"
}

export enum UnaryOperator {
    Not = "not"
}

export enum MathConstant {
    Pi = "pi",
    E = "e",
    Tau = "tau",
    Alpha = "alpha",
    Beta = "beta",
    Gamma = "gamma",
    Delta = "delta",
    Epsilon = "epsilon",
    Zeta = "zeta",
    Eta = "eta",
    Theta = "theta",
    Vartheta = "vartheta",
    Iota = "iota",
    Kappa = "kappa",
    Lambda = "lambda",
    Mu = "mu",
    Nu = "nu",
    Xi = "xi",
    Rho = "rho",
    Varrho = "varrho",
    Sigma = "sigma",
    Varsigma = "varsigma",
    Upsilon = "upsilon",
    Phi = "phi",
    Varphi = "varphi",
    Chi = "chi",
    Psi = "psi",
    Omega = "omega",
    UpperGamma = "Gamma",
    UpperDelta = "Delta",
    UpperTheta = "Theta",
    UpperLambda = "Lambda",
    UpperXi = "Xi",
    UpperPi = "Pi",
    UpperSigma = "Sigma",
    UpperUpsilon = "Upsilon",
    UpperPhi = "Phi",
    UpperPsi = "Psi",
    UpperOmega = "Omega",
    Partial = "partial",
    Nabla = "nabla",
    Infty = "infty",
    Hbar = "hbar",
    Ell = "ell",
    Aleph = "aleph",
    Re = "Re",
    Im = "Im",
    Angle = "angle",
    Prime = "prime",
    Ldots = "ldots",
    Cdots = "cdots",
    Vdots = "vdots",
    Ddots = "ddots"
}

export enum MathFunction {
    Sqrt = "sqrt",
    Fact = "fact",
    Sin = "sin",
    Cos = "cos",
    Tan = "tan",
    Cot = "cot",
    Sec = "sec",
    Csc = "csc",
    Arcsin = "arcsin",
    Arccos = "arccos",
    Arctan = "arctan",
    Sinh = "sinh",
    Cosh = "cosh",
    Tanh = "tanh",
    Ln = "ln",
    Exp = "exp",
    Abs = "abs",
    Log = "log",
    Gcd = "gcd",
    Deg = "deg",
    Det = "det",
    Dim = "dim",
    Ker = "ker",
    Arg = "arg",
    Sum = "sum",
    Prod = "prod",
    Coprod = "coprod",
    Bigcup = "bigcup",
    Bigcap = "bigcap",
    Bigvee = "bigvee",
    Bigwedge = "bigwedge",
    Bigoplus = "bigoplus",
    Bigotimes = "bigotimes",
    Bigsqcup = "bigsqcup"
}

export enum MathAccent {
    Hat = "hat",
    Vec = "vec",
    Bar = "bar",
    Tilde = "tilde",
    Dot = "dot",
    Ddot = "ddot",
    Overline = "overline"
}

export const OPERATOR_PRECEDENCE = {
    [BinaryOperator.Or]: 1,
    [BinaryOperator.And]: 2,
    [BinaryOperator.LessThan]: 3,
    [BinaryOperator.GreaterThan]: 3,
    [BinaryOperator.LessOrEqual]: 3,
    [BinaryOperator.GreaterOrEqual]: 3,
    [BinaryOperator.Equal]: 3,
    [BinaryOperator.NotEqual]: 3,
    [BinaryOperator.Add]: 4,
    [BinaryOperator.Subtract]: 4,
    [BinaryOperator.Multiply]: 5,
    [BinaryOperator.Divide]: 5,
    [BinaryOperator.Power]: 6
} as const satisfies Record<BinaryOperator, number>;
