export enum ExpressionKind {
    Number = "number",
    Variable = "variable",
    Constant = "constant",
    Call = "call",
    Negate = "negate",
    Not = "logical-not",
    Binary = "binary"
}

export enum BinaryOperator {
    Add = "+",
    Subtract = "-",
    Multiply = "*",
    Divide = "/",
    Power = "^",
    LessThan = "<",
    GreaterThan = ">",
    LessOrEqual = "<=",
    GreaterOrEqual = ">=",
    Equal = "==",
    NotEqual = "!=",
    And = "and",
    Or = "or",
    Approx = "~~",
    Equiv = "===",
    Cong = "~==",
    Sim = "~",
    Simeq = "~=",
    Ll = "<<",
    Gg = ">>",
    In = "in",
    Notin = "notin",
    Ni = "ni",
    Parallel = "||",
    Mid = "|",
    Perp = "-|",
    To = "to",
    Gets = "gets",
    Mapsto = "mapsto",
    Uparrow = "uparrow",
    Downarrow = "downarrow",
    Leftrightarrow = "leftrightarrow",
    Longleftarrow = "longleftarrow",
    Longrightarrow = "longrightarrow",
    Hookrightarrow = "hookrightarrow",
    LeftarrowDouble = "Leftarrow",
    RightarrowDouble = "Rightarrow",
    LeftrightarrowDouble = "Leftrightarrow",
    Implies = "implies",
    Iff = "iff"
}

export enum UnaryOperator {
    Not = "not"
}

export enum MathConstant {
    Pi = "pi",
    E = "e",
    Tau = "tau",
    Alpha = "alpha",
    Beta = "beta",
    Gamma = "gamma",
    Delta = "delta",
    Epsilon = "epsilon",
    Zeta = "zeta",
    Eta = "eta",
    Theta = "theta",
    Vartheta = "vartheta",
    Iota = "iota",
    Kappa = "kappa",
    Lambda = "lambda",
    Mu = "mu",
    Nu = "nu",
    Xi = "xi",
    Rho = "rho",
    Varrho = "varrho",
    Sigma = "sigma",
    Varsigma = "varsigma",
    Upsilon = "upsilon",
    Phi = "phi",
    Varphi = "varphi",
    Chi = "chi",
    Psi = "psi",
    Omega = "omega",
    UpperGamma = "Gamma",
    UpperDelta = "Delta",
    UpperTheta = "Theta",
    UpperLambda = "Lambda",
    UpperXi = "Xi",
    UpperPi = "Pi",
    UpperSigma = "Sigma",
    UpperUpsilon = "Upsilon",
    UpperPhi = "Phi",
    UpperPsi = "Psi",
    UpperOmega = "Omega",
    Partial = "partial",
    Nabla = "nabla",
    Infty = "infty",
    Hbar = "hbar",
    Ell = "ell",
    Aleph = "aleph",
    Re = "Re",
    Im = "Im",
    Angle = "angle",
    Prime = "prime",
    Ldots = "ldots",
    Cdots = "cdots",
    Vdots = "vdots",
    Ddots = "ddots"
}

export enum MathFunction {
    Sqrt = "sqrt",
    Root = "root",
    Fact = "fact",
    Sin = "sin",
    Cos = "cos",
    Tan = "tan",
    Cot = "cot",
    Sec = "sec",
    Csc = "csc",
    Arcsin = "arcsin",
    Arccos = "arccos",
    Arctan = "arctan",
    Sinh = "sinh",
    Cosh = "cosh",
    Tanh = "tanh",
    Ln = "ln",
    Exp = "exp",
    Abs = "abs",
    Log = "log",
    Gcd = "gcd",
    Deg = "deg",
    Det = "det",
    Dim = "dim",
    Ker = "ker",
    Arg = "arg",
    Sum = "sum",
    Prod = "prod",
    Coprod = "coprod",
    Bigcup = "bigcup",
    Bigcap = "bigcap",
    Bigvee = "bigvee",
    Bigwedge = "bigwedge",
    Bigoplus = "bigoplus",
    Bigotimes = "bigotimes",
    Bigsqcup = "bigsqcup"
}

export enum MathIntegral {
    Int = "int",
    Oint = "oint",
    Iint = "iint",
    Iiint = "iiint"
}

export enum MathLimit {
    Lim = "lim",
    Limsup = "limsup",
    Liminf = "liminf",
    Sup = "sup",
    Inf = "inf",
    Limmax = "limmax",
    Limmin = "limmin"
}

export enum MathAccent {
    Hat = "hat",
    Vec = "vec",
    Bar = "bar",
    Tilde = "tilde",
    Dot = "dot",
    Ddot = "ddot",
    Overline = "overline"
}

export const OPERATOR_PRECEDENCE = {
    [BinaryOperator.To]: 1,
    [BinaryOperator.Gets]: 1,
    [BinaryOperator.Mapsto]: 1,
    [BinaryOperator.Uparrow]: 1,
    [BinaryOperator.Downarrow]: 1,
    [BinaryOperator.Leftrightarrow]: 1,
    [BinaryOperator.Longleftarrow]: 1,
    [BinaryOperator.Longrightarrow]: 1,
    [BinaryOperator.Hookrightarrow]: 1,
    [BinaryOperator.LeftarrowDouble]: 1,
    [BinaryOperator.RightarrowDouble]: 1,
    [BinaryOperator.LeftrightarrowDouble]: 1,
    [BinaryOperator.Implies]: 1,
    [BinaryOperator.Iff]: 1,
    [BinaryOperator.Or]: 2,
    [BinaryOperator.And]: 3,
    [BinaryOperator.LessThan]: 4,
    [BinaryOperator.GreaterThan]: 4,
    [BinaryOperator.LessOrEqual]: 4,
    [BinaryOperator.GreaterOrEqual]: 4,
    [BinaryOperator.Equal]: 4,
    [BinaryOperator.NotEqual]: 4,
    [BinaryOperator.Approx]: 4,
    [BinaryOperator.Equiv]: 4,
    [BinaryOperator.Cong]: 4,
    [BinaryOperator.Sim]: 4,
    [BinaryOperator.Simeq]: 4,
    [BinaryOperator.Ll]: 4,
    [BinaryOperator.Gg]: 4,
    [BinaryOperator.In]: 4,
    [BinaryOperator.Notin]: 4,
    [BinaryOperator.Ni]: 4,
    [BinaryOperator.Parallel]: 4,
    [BinaryOperator.Mid]: 4,
    [BinaryOperator.Perp]: 4,
    [BinaryOperator.Add]: 5,
    [BinaryOperator.Subtract]: 5,
    [BinaryOperator.Multiply]: 6,
    [BinaryOperator.Divide]: 6,
    [BinaryOperator.Power]: 7
} as const satisfies Record<BinaryOperator, number>;
