export enum NotationKind {
    Identifier = "identifier",
    Number = "number",
    Operator = "operator",
    Row = "row",
    Fenced = "fenced",
    Fraction = "fraction",
    Superscript = "superscript",
    Subscript = "subscript",
    Radical = "radical",
    Accent = "accent"
}

// An accent command decorates the single argument that follows it (`\hat{x}`), unlike an operator that stands alone.
export enum LatexAccentCommand {
    Hat = "hat",
    Vec = "vec",
    Bar = "bar",
    Tilde = "tilde",
    Dot = "dot",
    Ddot = "ddot",
    Overline = "overline"
}

// Commands that take braced arguments rather than standing for a glyph, so the parser reads their operands.
export enum LatexStructuralCommand {
    Frac = "frac",
    Sqrt = "sqrt"
}

export enum OperatorChar {
    Plus = "+",
    Minus = "-",
    Equal = "=",
    Less = "<",
    Greater = ">",
    Slash = "/",
    Comma = ",",
    Bang = "!"
}

export enum LatexOperatorCommand {
    Le = "le",
    Leq = "leq",
    Ge = "ge",
    Geq = "geq",
    Ne = "ne",
    Neq = "neq",
    Ll = "ll",
    Gg = "gg",
    Prec = "prec",
    Succ = "succ",
    Preceq = "preceq",
    Succeq = "succeq",
    Approx = "approx",
    Equiv = "equiv",
    Cong = "cong",
    Simeq = "simeq",
    Sim = "sim",
    Asymp = "asymp",
    Propto = "propto",
    Parallel = "parallel",
    Mid = "mid",
    Perp = "perp",
    In = "in",
    Notin = "notin",
    Ni = "ni",
    Cup = "cup",
    Cap = "cap",
    Subset = "subset",
    Subseteq = "subseteq",
    Supset = "supset",
    Supseteq = "supseteq",
    Setminus = "setminus",
    Emptyset = "emptyset",
    Cdot = "cdot",
    Times = "times",
    Div = "div",
    Pm = "pm",
    Mp = "mp",
    Ast = "ast",
    Star = "star",
    Circ = "circ",
    Bullet = "bullet",
    Diamond = "diamond",
    Oplus = "oplus",
    Ominus = "ominus",
    Otimes = "otimes",
    Oslash = "oslash",
    Odot = "odot",
    Dagger = "dagger",
    Ddagger = "ddagger",
    Sqcup = "sqcup",
    Sqcap = "sqcap",
    Uplus = "uplus",
    Land = "land",
    Lor = "lor",
    Wedge = "wedge",
    Vee = "vee",
    Neg = "neg",
    Lnot = "lnot",
    Forall = "forall",
    Exists = "exists",
    Top = "top",
    Bot = "bot",
    To = "to",
    Mapsto = "mapsto",
    Implies = "implies",
    Iff = "iff",
    Rightarrow = "Rightarrow",
    Leftrightarrow = "Leftrightarrow",
    Sum = "sum",
    Prod = "prod",
    Coprod = "coprod",
    Bigcup = "bigcup",
    Bigcap = "bigcap",
    Bigvee = "bigvee",
    Bigwedge = "bigwedge",
    Bigoplus = "bigoplus",
    Bigotimes = "bigotimes",
    Bigsqcup = "bigsqcup",
    Int = "int",
    Oint = "oint",
    Iint = "iint",
    Iiint = "iiint"
}
